### ISSUE TITLE
Pr2: en `losQueLeGanan` estás dependiendo de la forma de calcular cuándo un Pokémon le gana a otro

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#12]
Básicamente, estás haciendo que esa función dependa del significado de ganar. Si luego lo queremos cambiar para que los Pokémon peleen más allá de su tipo (por ejemplo, por nivel), entonces esta función deja de andar. Siempre es bueno que las responsabilidades queden acotadas a las funciones que les corresponden. En este caso, contar cuántos ganan es cuestión de contar, y no de saber cómo pelean. Deberías utilizar una función que dados 2 Pokémon diga cuál gana...

**Comment by MelinaJimenez** [comment]
Se actualizo la practica con los errores corregidos

**Comment by fidel-ml** [comment]
No veo que haya cambiado. Sigue dependiendo de que la pelea entre Pokémon se resuelva solamente por tipo... Pensá qué pasa si cambiamos la forma de pelear para que incluya otras cosas: tu función deja de funcionar... :(

**Comment by fidel-ml** [comment]
Muchísimo mejor. :)
