### ISSUE TITLE
Pr2: `esSenior` hace doble PM.

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#16]
Esto pocas veces es feliz, y nunca cuando no se lo necesita...

**Comment by MelinaJimenez** [comment]
Se modifico la función esSenior

**Comment by fidel-ml** [comment]
Yo sigo viendo el doble PM... No tenés que usar DOS constructores en el mismo pattern...

**Comment by MelinaJimenez** [comment]
Se actualiza practica 2
