### ISSUE TITLE
Pr2: la función `asignadosPorProyecto` recorre la empresa muchas veces

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#17]
Si usás recursión estructural en lugar de 400 subtareas, sale con mucho menos esfuerzo...

**Comment by MelinaJimenez** [comment]
Se actualiza practica 2

**Comment by fidel-ml** [comment]
No cambió nada sustancial. El tema es no mirar la empresa entera para cada proyecto.
Tenés que hacer recursión sobre los roles, y agregar cada proyecto al resultado recursivo de forma interesante...

**Comment by MelinaJimenez** [comment]
se modifico la función asignadosPorProyecto
