### ISSUE TITLE
Pr3: `pasosHastaTesoro` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#21]
Está contando mal, pues cuando encuentra un tesoro, sigue buscando. Si tenés que dar los pasos hasta el 1er tesoro, esto no es correcto.

**Comment by MelinaJimenez** [comment]
Se modifico la función pasosHastaTesoro

**Comment by fidel-ml** [comment]
La veo exactamente igual. Tenés que DETENERTE cuando encontrás un tesoro, y no seguir contando...
Por favor, preguntá cuando no entendés una corrección...

**Comment by MelinaJimenez** [comment]
se actualizo la practica
