### ISSUE TITLE
Pr3: `leaves` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#24]
Básicamente, devuelve todos los nodos y no las hojas...
Además, si lo que querés es devolver todo, el 2do caso es innecesario (pero NO para hacerla bien... ;))

**Comment by MelinaJimenez** [comment]
Se modifico la función leaves

**Comment by fidel-ml** [comment]
Ahora está mejor, pero si sabés que los subárboles son vacíos, ¿para qué llamar a la recursión sobre ellos?

**Comment by MelinaJimenez** [comment]
Modifique la recursión que estaba implementando en el then
