### ISSUE TITLE
Pr3: `listPerLevel` sería más eficiente usando recursión estructural sobre el árbol

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#25]
Ahora está usando recursión estructural sobre la altura, y eso hace que se recorra el árbol más veces de lo necesario.

Además en la auxiliar estás preguntando a cada paso por una cantidad negativa que NO puede suceder. Si querés atender ese caso (que por ser una auxiliar no lo amerita), tenés que recordar lo que vimos en clase sobre funciones wrapper...

**Comment by MelinaJimenez** [comment]
Se modifico la función listPerLevel
