### ISSUE TITLE
Pr3: `armarNegacion` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#27]
Nunca arma una negación... Básicamente en el segundo caso ¿por qué devolvés lo mismo, si hay que armar una negación?

**Comment by MelinaJimenez** [comment]
Se actualizo el ejercicio

**Comment by fidel-ml** [comment]
Ahora eliminaste no solamente `armarNegacion`, sino también la recursión de ese caso. Empeoraste el código.
Si no entendés cómo arreglar un código, no adivines: preguntá. Es muy desgastante corregirles 10 veces lo mismo...

**Comment by MelinaJimenez** [comment]
volvi a agregar la funcion que borre y agregue lo que  me falto de el armarNegacion
