### ISSUE TITLE
Pr3: `armarNegacion` no es correcta

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#35]
Porque es una auxiliar que debe ARMAR una negación según sea el argumento. Y lo que hace es sacar doble negación directamente, sin agregar nada, por lo que cambia el significado...
Funciona por propiedades accidentales de la negación, pero no es feliz que sea así.

**Comment by MelinaJimenez** [comment]
Se elimino la función armarNegación y se modifico la función Simplificar

**Comment by fidel-ml** [comment]
Y ahora está MUY mal. Ver issue #27
