### ISSUE TITLE
Pr 2: En `aplanar`, es feliz usar nombre de listas para las listas

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#5]
Si un argumento tiene tipo `[a]` entonces es feliz llamarlo `xs` y no `x` (vendría de muchaS `x`). Esto permite identificar más fácilmente de qué va la función, sin necesidad de estar todo el tiempo haciendo saltos mentales.
Consecuentemente, si un argumento tiene tipo `[[a]]` lo llamamos `xss` (o sea, muchaS `xs`).

**Comment by MelinaJimenez** [comment]
Se corrigió el nombre de la lista

**Comment by fidel-ml** [comment]
JAJA. Pero el elemento se sigue llamando `x`... La idea es que cualquier cosa que sea una lista `[a]` se llame con una s (como `xs`), y si es una lista de listas, `[[a]]` entonces se llama con 2 eses (como `xss`). Etc.

**Comment by MelinaJimenez** [comment]
Se actualizo la practica con los errores corregidos
