### ISSUE TITLE
Pr2: la segunda ecuación de `agregar` es innecesaria

### ISSUE THREAD

**Issue by fidel-ml** [MelinaJimenez/EstrD22s1#7]
NO tenés que mirar más de un argumento NUNCA, a menos que sea imposible hacerlo de otra manera.
Cuando lo hacés, estás garantizando o bien que vas a perder casos, o bien que vas a tener casos de más y consecuentemente tener más chances de error. Además, trabajás de más, lo que nunca es feliz...

**Comment by MelinaJimenez** [comment]
Se actualizo la practica con los errores corregidos
